import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { getServerSession } from 'next-auth'

import AsideBar from '@/components/aside-bar'
import { ClientProvider } from '@/components/Provider'
import SessionProvider from '@/components/session-provider'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* <AsideBar /> */}
            <SessionProvider session={session}>{children}</SessionProvider>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
