import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { getServerSession } from 'next-auth'

import AsideBar from '@/components/aside-bar'
import SessionProvider from '@/components/providers/session-provider'
import { ClientProvider } from '@/components/providers/tanstack-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider session={session}>
              <AsideBar />
              {children}
              <SpeedInsights />
              <Analytics />
            </SessionProvider>
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
